[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
via-ir = true
optimizer = true
optimizer_runs = 1_000_000 # etherscan max
bytecode_hash = 'none'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

