[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
via-ir = true
optimizer = true
optimizer_runs = 999_999_999

# See more config options https://github.com/foundry-rs/foundry/tree/master/config